# Generated by Django 4.0.2 on 2022-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_categories_locations_alter_images_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ManyToManyField(to='photos.Categories'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
